services:
  oracle-db:
    image: gvenzl/oracle-free:latest
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=oracle
      - ORACLE_DATABASE=XEPDB1  # Fuerza la creación de XEPDB1
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./oracle-init:/container-entrypoint-initdb.d
    healthcheck:
      test: >
        sh -c "
          [ -f /opt/oracle/oradata/.db_ready ] && 
          echo 'SELECT 1 FROM dual;' | 
          sqlplus -s system/oracle@//localhost:1521/XEPDB1 > /dev/null
        "
      interval: 15s
      timeout: 30s
      retries: 30
      start_period: 120s  # Tiempo extra para Oracle

  books-authors-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      oracle-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-db:1521/XEPDB1?connect_timeout=30&retry_count=5
      - SPRING_DATASOURCE_USERNAME=system
      - SPRING_DATASOURCE_PASSWORD=oracle
      - SPRING_DATASOURCE_HIKARI_INITIALIZATION_FAIL_TIMEOUT=60000
      - SPRING_DATASOURCE_HIKARI_VALIDATION_TIMEOUT=5000
      - SPRING_JPA_PROPERTIES_HIBERNATE_HIKARI_INITIALIZATION_FAIL_TIMEOUT=60000

volumes:
  oracle-data:
